version: "3.5"
services:
  app:
    image: alifnaufalyasin/gits-capstone-project:latest
    # pull_policy: always
    networks:
      - database
    container_name: smart-server
    ports:
      - "4132:4132"
    # links:
    #   - db
    # depends_on:
    #   db: 
    #     condition: service_healthy
    expose:
      - "4132"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=10123
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - SECRET=gitscapstoneproject
      - PORT=4132
      - RESET_TABLES=true
      - SEED_TABLES=true
      - EMAIL=design.email
      - PASSWORD_EMAIL=password
      - FIREBASE_API_KEY=AAAAPB7DZ3k:APA91bEdWRKIYHYVwxqHtW_fWxnX01kLZOMxGglwhDi4SN1XU8Uth9j05f6bXS-l-kVVPNjdSXxpX96EKEDALroaUd5yPKJNcp6B4cRVNPT8PiCE3oNLvRmG-iKN5DW-rKtsYGj8hWsi
    restart: "unless-stopped"

networks:
  database:
    name: database
    external: true
    
  # db:
  #   image: postgres:13.4-alpine
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   container_name: smart-postgres
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: "unless-stopped"
