name: "Deploy VPS"

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types: [completed]
    
jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/gits-smart
            docker-compose down
            git pull origin master
            docker-compose pull
            docker-compose up -d
